---
apiVersion: v1
kind: Service
metadata:
  name: web-server
spec:
  selector:
    svc: web-server
  ports:
  - port: 1323
    protocol: TCP
    targetPort: 1323

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    svc: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: web-server
  template:
    metadata:
      name: web-server
      labels:
        svc: web-server
    spec:
      containers:
      - name: web-server
        image: ghcr.io/heimonsy/goservices:webserver-v0.2.1
        ports:
        - containerPort: 1323
        readinessProbe:
          tcpSocket:
            port: 1323
          initialDelaySeconds: 5
          periodSeconds: 5

